### Site metadata ###

title: Toast Coetzer

description: >-
  Homepage for Toast Coetzer, a South African writer and frontman for the Buckfever Underground.

twitter_username: The_Buckfever
instagram_username: toastcards

### Build settings ###

url: "https://toastcoetzer.com"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

google_analytics: UA-87705880-10
rss: rss

exclude:
  - LICENSE
  - README.md
  - Makefile
