### Site metadata ###

title: Toast Coetzer

description: |
  Homepage for Toast Coetzer, a South African writer and frontman for the Buckfever Underground.

twitter_username: The_Buckfever
instagram_username: toastcards

### Build settings ###

url: https://toastcoetzer.com

theme: minima

header_pages:
  - writing.md
  - drawing.md
  - photography.md
  - ons-klyntji.md
  - contact.md

permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap

google_analytics: UA-87705880-10
rss: subscribe

exclude:
  - LICENSE
  - README.md
  - Makefile
