### Site metadata ###

title: Toast Coetzer

description: >-
  Homepage for Toast Coetzer, a South African writer and frontman for the Buckfever Underground.

email: info@toastcoetzer.com
twitter_username: The_Buckfever

### Build settings ###

url: ""

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - LICENSE
  - README.md
  - Makefile
