# Jekyll config.
#
# You can use this file to set fields recognized by Jekyll or plugins and also
# any custom field names which you want to use in your site.
#
# Though, this config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please stop and start server.

### Site metadata ###

# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jekyll Blog Demo

# If you leave the description blank and publish to Github Pages, it will take your Git
# repo's description. At least the way the theme is setup.
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

email: your-email@example.com
twitter_username: jekyllrb
github_username: jekyll

### Build settings ###

# Your website will be served on: {url}/{baseurl}
#     e.g. https://MichaelCurrin.github.com/jekyll-blog-demo
# So set this up using the next two parameters.

# The base hostname AND protocol for your site, e.g. 'https://example.com'.
# Do not use a trailing forward slash.
# This value ONLY applied for a prod build:
#  - By deploying to Github Pages
#  - Or when setting JEKYLL_ENV='production' as an environment variable locally
#    or on Netlify.
# It is recommended to set this at least for the canonical tag to be aware of the full domain,
# as that is recommended but not required for use by crawlers.
url: "https://michaelcurrin.github.io"
# If using Github Pages as a project site (USERNAME.github.io/my-project),
# this should be a forwardslash, followed by the name of your repo.
# Your site will be served from this URL so all URLs on the page should relative to this too.
#
# If using a Github Pages as a user site (USERNAME.github.io/)
# or using Netlify, this can be empty.
baseurl: "/jekyll-blog-demo"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Include for processing

# Jekyll will not process paths starting an underscore or dot, except of course
# the underscore directories which it expects like _posts.
# You can force inclusions here. For example, if you don't want to keep your
# pages in the top-level directory.
# include:
#   - '_pages'

# Exclude from processing

# We want to only copy to the _site directory the files and directories which we want to be
# served publically.

# Jekyll will ignore files starting with a dot or underscore, but there are other files we
# want to ignore. So set these below in your `exclude `field. The Makefile line can be
# omitted if you do not have one. The slash is optional but helps indicate directories vs files.

exclude:
  - LICENSE
  - README.md
  - Makefile

  # In Jekyll 4, these are always excluded, so you never have to add them to your list.
  # But in Jekyll 3, these are needed:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
# For more precise control:
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Also add these if relevant for your project:
# - bin/
# - docs/
